<div style="background-color: #eeeeef; padding: 50px 0; "><div style="max-width:640px; margin:0 auto; "><div style="padding: 20px; background-color: rgb(255, 255, 255);">            <p class="MsoNormal" align="center" style="text-align:center"><b><span style="font-size:18.0pt;font-family:" arial",sans-serif"="">EMPLOYMENT
CONTRACT<o:p></o:p></span></b></p><p class="MsoNormal" align="center" style="text-align:center"><b><span style="font-size:18.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></b></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">This
employment agreement (“Agreement”) is made and effective as of&nbsp;</span><span style="font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">{CONTRACT_EFFECTIVE_DATE} to&nbsp;</span><span style="font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">{CONTRACT_EXPIRATION_DATE}</span><span style="font-family: Arial, sans-serif; font-size: 11pt; font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">&nbsp;by and between:</span></p><p class="MsoNormal" style="margin-left:36.0pt"><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">Employer</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">:&nbsp;</span>{COMPANY_NAME}<span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">, (“Employer”), and</span></p><p class="MsoNormal" style="margin-left:36.0pt"><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">Employee</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">:&nbsp;</span>{STAFF_FIRST_NAME} {STAFF_LAST_NAME}<span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">, (“Employee”) with a
mailing address of&nbsp;</span><span style="font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">{STAFF_EMAIL}</span><span style="font-family: Arial, sans-serif; font-size: 11pt; font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">.</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">WHEREAS
the Employer intends to hire the Employee for the Position and the Employee
desires to provide their services to the Employer for payment.</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">IN
CONSIDERATION of promises and other good and valuable consideration, the
parties agree to the following:<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">I. EMPLOYEE DUTIES</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee agrees
that they will act in accordance with this Agreement and with the best
interests of the Employer in mind, which may or may not require them to present
the best of their skills, experience, and talents, to perform all the duties
required of the Position. In carrying out the duties and responsibilities of
their Position, the Employee agrees to adhere to any and all policies,
procedures, rules, regulations, as administered by the Employer. In addition,
the Employee agrees to abide by all local, county, State, and Federal laws
while employed by the Employer.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">II. RESPONSIBILITIES</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee shall be
given the job title of&nbsp;</span>{STAFF_POSITION}<span style="font-size:11.0pt;font-family:" arial",sans-serif"="">, (“Position”) which shall involve:&nbsp;</span>{STAFF_POSITON_DESCRIPTION}<span style="font-size:11.0pt;font-family:" arial",sans-serif"="">.</span></p><p class="MsoNormal"><span style="font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align); font-size: 11pt; font-family: Arial, sans-serif;">The
Employer may also assign duties to the Employee from time to time by the
Employer.</span></p><p class="MsoNormal"><span style="text-align: var(--bs-body-text-align);"><font face="Arial, sans-serif" style=""><span style="font-size: 14.6667px;">Type of employee contract: {CONTRACT_TYPE}.</span></font></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">III. EMPLOYMENT PERIOD</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employer agrees
to hire the Employee: (check one)<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt;tab-stops:52.65pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-368220469"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt>
- </span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">At-Will</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> which means this Agreement may be terminated
at any time by either the Employee or Employer. After termination by any of the
Parties, neither will have any obligation other than the non-disclosure of the
Employer’s proprietary information as outlined in Section XII and any
non-compete listed in Section XIII.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;tab-stops:52.65pt"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpFirst" style="margin-left:107.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l2 level1 lfo1;tab-stops:52.65pt"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">a.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employee’s Termination</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee shall
have the right to terminate this Agreement by providing at least ___ days’
notice. <a name="OLE_LINK3"></a><a name="OLE_LINK4">If the Employee should terminate this Agreement, he or she shall be entitled
to severance, equal to their pay at the time of termination, for a period of
___________________.</a><o:p></o:p></span></p><p class="MsoListParagraphCxSpLast" style="margin-left:107.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l2 level1 lfo1;tab-stops:52.65pt"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">b.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employer’s Termination</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employer shall
have the right to terminate this Agreement by providing at least ___ days’
notice. If the Employer should terminate this Agreement, the Employee shall be
entitled to severance, equal to their pay at the time of termination, for a
period of ___________________.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;tab-stops:52.65pt"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt;tab-stops:52.65pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="945812774"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">-
<b>For a Specified Time-Period</b>
beginning on the ___ day of ___________________, 20___ and ending on the ___
day of ___________________, 20___. At the end of said time-period, both parties
will no longer have any obligation to one another.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt;tab-stops:52.65pt"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpFirst" style="margin-left:107.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l0 level1 lfo2;tab-stops:52.65pt"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">a.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employee’s Termination</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-895657764"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> *</span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-2105866942"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall not</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> have the right to
terminate this Agreement. *If allowed, the Employee shall be required to
provide at least ___ days’ notice. If the Employee should terminate this Agreement
before the expiration date, he or she shall be entitled to severance, equal to
their pay at the time of termination, for a period of ___________________.<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-left:107.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l0 level1 lfo2;tab-stops:52.65pt"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">b.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employer’s Termination</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employer </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="294646476"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> *</span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1642537108"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall not</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> have the right to
terminate this Agreement. *If allowed, the Employer shall be required to
provide at least ___ days’ notice. If the Employer should terminate this
Agreement, the Employee shall be entitled to severance, equal to their pay at
the time of termination, for a period of ___________________.<o:p></o:p></span></p><p class="MsoListParagraphCxSpLast" style="margin-left:71.0pt;mso-add-space:auto;
tab-stops:52.65pt"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">IV. PAY</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. As compensation for
the services provided, the Employee shall be paid ___________________ dollars
($___________________) </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="440736374"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> <b>per hour</b>
</span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1976482748"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> <b>salary on an annual basis </b>(“Compensation”). The Compensation is a
gross amount that is subject to all local, State, Federal, and any other taxes
and deductions as prescribed by law. Payment shall be distributed to the
Employee on a </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="764966327"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> <b>weekly </b></span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1238053717"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> <b>bi-weekly </b></span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1289344557"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> <b>monthly
</b></span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="734672169"><span style="font-family:" ms="" gothic""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> <b>quarterly </b></span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-2106249435"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> <b>annual </b>basis.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpFirst" style="margin-left:54.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l1 level1 lfo3"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">a.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Commissions</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. In addition to the
aforementioned Pay, the Employee shall be entitled to commissions that are to
be paid every ___________________ and shall be calculated as follows:
__________________________________________________<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-left:54.0pt;mso-add-space:
auto"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">______________________________________________________________________________________________________________________________________<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-left:54.0pt;mso-add-space:
auto"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="margin-left:54.0pt;mso-add-space:
auto;text-indent:-18.0pt;mso-list:l1 level1 lfo3"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">b.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Bonus</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee shall be
entitled to Bonuses on a ___________________ basis which is to be calculated as
follows: __________________________________<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle" style="margin-left:54.0pt;mso-add-space:
auto"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">______________________________________________________________________________________________________________________________________<o:p></o:p></span></p><p class="MsoListParagraphCxSpLast" style="margin-left:54.0pt;mso-add-space:auto"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">V. EMPLOYEE BENEFITS</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. During the period of
employment, the Employee shall be eligible to participate in benefits
established by the Employer. These include _______________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">________________________________________________________________________________________________________________________________________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">The
aforementioned benefits may change at any time by the Employer. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">VI. OUT-OF-POCKET
EXPENSES</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">.
The Employer agrees to reimburse the Employee for any expenses that are
incurred, including: (check all that apply)<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1258331625"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Travel<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1658108975"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Food<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1996750064"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Lodging<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-385332174"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Other: _____________________________________________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">VII. OWNERSHIP INTEREST</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. This Agreement shall </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1644493399"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">not include </span></b><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="189811153"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> *<b>include</b> partial ownership in the business operations of the
Employer. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">*If
such ownership is offered, the details shall be stated in an attached Exhibit.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">VIII. TRIAL PERIOD</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. Other than certain
benefits prescribed by law, the Employee will not be eligible for Benefits,
Vacation Time, or Personal Leave until after the first ___ days of employment
("Trial Period"). In addition, the Employee will not be eligible for
vacation time, sick leave, or any time off that would be paid or unpaid. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">IX. VACATION TIME</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. After the Trial
Period is complete, the Employee is entitled to ___ days off per year of which
is required to be mutually benefiting of the Employer and the Employee. It is
required for the Employee to give notice before scheduling their vacation in
accordance with Company policy.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Any
unused Vacation Time shall be (check one):<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="595832045"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Converted
to cash at the end of the year at a rate of $___ per day.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1383059507"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Eligible
to rollover up to ___ days to the next year.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1102775903"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">-
Forfeited at the end of the year.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="623425166"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Other: _____________________________________________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">X. PERSONAL LEAVE</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. After the Trial
Period, the Employee shall be eligible for ___ days of </span><a name="OLE_LINK1"></a><a name="OLE_LINK2"></a><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1643422226"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span><span style="font-family:" arial",sans-serif"=""></span></w:sdt><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">paid</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> </span><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1434400148"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span><span style="font-family:" arial",sans-serif"=""></span></w:sdt><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">unpaid</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> time off per year for
personal and/or medical issues. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Any
unused Personal Leave shall be: (check one)<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1034418832"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Converted
to cash at the end of the year at a rate of $___ per day.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1318801353"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">- Eligible
to rollover up to ___ days to the next year.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-689531811"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">-
Forfeited at the end of the year.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="47958656"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">-
Other: _____________________________________________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">If
for any reason the Employee depletes their amount of days of personal leave in
a given year, he or she </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1714772140"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">may</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1482193359"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">may not </span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">be able to use any remaining vacation time. <o:p></o:p></span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></b></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XI. FEDERAL HOLIDAYS</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee shall be
entitled to ___ federal holidays per calendar year. This is subject to change
by the Employer from time to time. If for any reason the Employee should
request a Federal Holiday off, the Employer shall determine if the Employee may
do so and if it shall be taken from either the Employee’s Personal Leave or
Vacation Time. Federal Holidays are determined by the Employer and may change
every calendar year.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XII. CONFIDENTIALITY</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee
understands and agrees to keep any and all information confidential regarding
the business plans, inventions, designs, products, services, processes, trade
secrets, copyrights, trademarks, customer information, customer lists, prices,
analytics data, costs, affairs, and any other information that could be
considered proprietary to the Employer ("Confidential Information").
The Employee understands that disclosure of any such Confidential Information,
either directly or indirectly, shall result in litigation with the Employer
eligible for equitable relief to the furthest extent of the law, including but
not limited to filing claims for losses and/or damages. In addition, if it is
found that the Employee divulged Confidential Information to a third (3<sup>rd</sup>)
party with the Employer shall be entitled any and all reimbursement for their
legal and attorney’s fees.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraph" style="text-indent:-18.0pt;mso-list:l4 level1 lfo4"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">a.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Post Termination</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. After the Employee
has terminated their employment with the Employer, the Employee shall be bound
to <b>Section XII</b> of this Agreement for
a period of ____ </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1317331089"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">Months</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-308024170"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">Years </span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">(“Confidentiality Term”). If the
Confidentiality Term is beyond any limit set by local, State, or Federal laws,
then the Confidentiality Term shall be the maximum allowed legal time frame.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XIII. NON-COMPETE</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. (check one)<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1346402822"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">There
shall be no Non-Compete established in this Agreement.<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="2134054133"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">During
the term of employment, the Employee understands that he or she will be subject
to learning proprietary information, including trade secrets, which could be
applied to competitors of the employer. Therefore, in order to protect the
fiduciary interests of the Employer, the Employee agrees to: (check all that
apply)<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:36.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="414828691"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Withhold
from working in the following industry(ies): ___________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">________________________________________________________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="301360411"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Withhold
from working for the following employer(s): ___________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">________________________________________________________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1522672787"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Withhold
from working in the same industry(ies) as the Employer in the following
area(s): __________________________________________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">________________________________________________________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-1214733106"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
- </span><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Other:
_______________________________________________________<o:p></o:p></span></p><p class="MsoNormal" style="margin-left:72.0pt"><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">________________________________________________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">This
Non-Compete shall be in effect for ____ </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-410774924"><span style="font-family:
 " segoe="" ui="" symbol",sans-serif;mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:="" "segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;
font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:"segoe="" symbol""="">
</span><b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"="">Months</span></b><span style="font-size:11.0pt;
font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="15044608"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Years</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> following the date of
Employee’s termination.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">This
Section shall be applied to the Employee engaging, directly or indirectly, any
competitive industry. This includes, but is not limited to: <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpFirst" style="text-indent:-18.0pt;mso-list:l3 level1 lfo5"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">&nbsp; &nbsp; &nbsp;a.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Communicating
with related business owners, partners, members, officers, or agents;<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle"><span style="font-size:11.0pt;font-family:
" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="text-indent:-18.0pt;mso-list:l3 level1 lfo5"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">&nbsp; &nbsp; b.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Being
employed by or consulting any related business;<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle"><span style="font-size:11.0pt;font-family:
" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpMiddle" style="text-indent:-18.0pt;mso-list:l3 level1 lfo5"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">&nbsp; &nbsp; c.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Being
self-employed in a related business; or<o:p></o:p></span></p><p class="MsoListParagraphCxSpMiddle"><span style="font-size:11.0pt;font-family:
" arial",sans-serif"="">&nbsp;</span></p><p class="MsoListParagraphCxSpLast" style="text-indent:-18.0pt;mso-list:l3 level1 lfo5"><!--[if !supportLists]--><span style="font-size:11.0pt;font-family:" arial",sans-serif;mso-fareast-font-family:="" arial"="">&nbsp; &nbsp; d.)<span style="font-variant-numeric: normal; font-variant-east-asian: normal; font-stretch: normal; font-size: 7pt; line-height: normal; font-family: " times="" new="" roman";"="">&nbsp;&nbsp;
</span></span><!--[endif]--><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Soliciting
any customer, client, affiliate, vendor, or any other relationship of the
Employer.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XIV. EMPLOYEE’S ROLE</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="-103893922"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> </span><span style="font-family:" arial",sans-serif"=""><w:sdt checkbox="t" checkboxischecked="f" checkboxvaluechecked="☒" checkboxvalueunchecked="☐" checkboxfontchecked="MS Gothic" checkboxfontunchecked="MS Gothic" id="1280459553"><span style="font-family:" segoe="" ui="" symbol",sans-serif;="" mso-fareast-font-family:"ms="" gothic";mso-bidi-font-family:"segoe="" symbol""="">☐</span></w:sdt></span><span style="font-size:11.0pt;font-family:" segoe="" ui="" symbol",sans-serif;mso-bidi-font-family:="" "segoe="" symbol""=""> </span><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">shall not</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"=""> have the right to act
in the capacity of the Employer. This includes, but is not limited to, making
written or verbal agreements with any customer, client, affiliate, vendor, or
third (3<sup>rd</sup>) party.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XV. APPEARANCE</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee must
appear at the Employer’s desired workplace at the time scheduled. If the
Employee does not appear, for any reason, on more than ____ separate occasions
in a 12-month calendar period, the Employer has the right to terminate this
Agreement immediately. In such event, the Employee would not be granted
severance as stated in Section III.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XVI. DISABILITY</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. If for any reason the
Employee cannot perform their duties, by physical or mental disability, the
Employer may terminate this Agreement by giving the Employee ____ days’ written
notice.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XVII. COMPLIANCE</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. The Employee agrees
to adhere to all sections of this Agreement in addition to any rules,
regulations, or conduct standards of the Employer, including obeying all local
and federal laws. If the Employee does not adhere to this Agreement, company
policies, including any task or obligation that is related to the
responsibilities of their Position, the Employer may terminate this Agreement
without severance as stated in Section III.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XVIII. RETURN OF
PROPERTY</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">.
The Employee agrees to return any and all property of the Employer upon the
termination of employment. This includes, but is not limited to, equipment,
electronics, records, access, notes, data, tests, vehicles, reports, models, or
any property that is requested by the Employer.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XIX. NOTICES</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. All notices that are
to be sent under this Agreement shall be done in writing and to be delivered
via Certified Mail (return receipt) to the following mailing addresses:<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" align="center" style="text-align:center"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employer<o:p></o:p></span></b></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal" align="center" style="text-align:center"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">Employee<o:p></o:p></span></b></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal" align="center" style="text-align:center"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">__________________________<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">The
aforementioned addresses may be changed with the act of either party providing
written notice. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XX. AMENDMENTS</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. This Agreement may be
modified or amended under the condition that any such amendment is attached and
authorized by all parties. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XXI. SEVERABILITY</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. This Agreement shall
remain in effect in the event a section or provision is unenforceable or
invalid. All remaining sections and provisions shall be deemed legally binding
unless a court rules that any such provision or section is invalid or
unenforceable, thus, limiting the effect of another provision or section. In
such case, the affected provision or section shall be enforced as so limited.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XXII. WAIVER OF
CONTRACTUAL RIGHT</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">S.
If the Employer or Employee fails to enforce a provision or section of this Agreement,
it shall not be determined as a waiver or limitation. Either party shall remain
the right to enforce and compel the compliance of this Agreement to its fullest
extent. <o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XXIII. GOVERNING LAW</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. This Agreement shall
be governed under the laws in the State of ___________________.<o:p></o:p></span></p><p class="MsoNormal"><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">&nbsp;</span></p><p class="MsoNormal"><b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">XXIV. ENTIRE AGREEMENT</span></b><span style="font-size:11.0pt;font-family:" arial",sans-serif"="">. This Agreement, along
with any attachments or addendums, represents the entire agreement between the
parties. Therefore, this Agreement supersedes any prior agreements, promises,
conditions, or understandings between the Employer and Employee. <o:p></o:p></span></p><p class="MsoNormal">{SIGNATURE}<br></p><p class="MsoNormal"><span style="font-size: 11pt; font-weight: var(--bs-body-font-weight); text-align: var(--bs-body-text-align);">&nbsp;</span><br></p>        </div>    </div></div>